name: Nightly CI run

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:

  ci:
    runs-on: ubuntu-latest
    env:
      CI: true
    outputs:
      results: ${{ steps.ci.outputs.results }}
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
    - uses: actions/checkout@v1
    - id: ci
      uses: ./.github/actions/ci

  create_issue:
    if: contains(needs.ci.outputs.results, 'failing')
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Create an issue
        uses: JasonEtco/create-an-issue@v2.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BODY: ${{ needs.ci.outputs.results }}
        with:
          filename: .github/ISSUE_TEMPLATE_NIGHLY_TESTS.md
          search_existing: all
          update_existing: true
      - name: Fail
        run: exit 1
