name: On pull request

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      CI: true
    outputs:
      results: ${{ steps.ci.outputs.results }}
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
    - uses: actions/checkout@v1
    - id: ci
      uses: ./.github/actions/ci

  post_errors_onto_pr:
    name: Post errors onto PR
    if: contains(needs.ci.outputs.results, 'failing')
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Comment on PR
        uses: mshick/add-pr-comment@v2
        with:
          proxy-url: https://add-pr-comment-proxy-j5iblm55gq-uc.a.run.app/
          message: |
            ❌ CI **FAILED** with the following output:

            <details>
            <summary>Unsuccessful test results</summary>
            <pre>${{ needs.ci.outputs.results }}</pre>
            </details>
      - name: Fail
        run: exit 1

  post_success_onto_pr:
    name: Post success message onto PR
    if: ${{ !contains(needs.ci.outputs.results, 'failing') }}
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Comment on PR
        uses: mshick/add-pr-comment@v2
        with:
          proxy-url: https://add-pr-comment-proxy-j5iblm55gq-uc.a.run.app/
          message: |
            ✅ CI **PASSED** with the following output:

            <details>
            <summary>Successful test results</summary>
            <pre>${{ needs.ci.outputs.results }}</pre>
            </details>
